import os
import pandas as pd
from router import query_model
from evaluator import MODELS, TOOL_DIR

EVAL_DIR = "evaluation_outputs"
QE_COLUMNS = ["QE1", "QE2", "QE3", "QE4", "QE5"]

YESNO_QE = ["QE1", "QE5"]
NUM_QE = ["QE2", "QE3", "QE4"]


def make_correction_prompt(user_story: str, diagram_code: str, invalid_qe: str, question: str) -> str:
    return f"""
You are correcting the following QE response for a PlantUML sequence diagram.

USER STORY:
{user_story}

SEQUENCE DIAGRAM:
{diagram_code}

QUESTION: {question}
INVALID RESPONSE: {invalid_qe}

Please respond with strictly the correct format:
- If Yes/No question (QE1/QE5), respond only 1 for Yes, 0 for No.
- If rating question (QE2-QE4), respond only a number between 1 and 10.

Do not add any explanation or text, only the number.
"""


def is_valid(qe, col):
    if col in YESNO_QE:
        return str(qe).strip() in ["0", "1", "Y", "y", "N", "n"]
    elif col in NUM_QE:
        try:
            val = int(qe)
            return 1 <= val <= 10
        except:
            return False
    return False

def correct_csv(csv_path):
    df = pd.read_csv(csv_path)

    for idx, row in df.iterrows():
        generated_by = row["Generated by"]
        model_name = row["Model"]

        if generated_by not in ["Tool", "GPT"]:
            continue  
        
        if model_name == "Human":
            continue
        diagram_file = f"{TOOL_DIR}/SD{idx+1}.txt" if generated_by=="Tool" else None
        diagram_code = open(diagram_file).read() if diagram_file else row.get("Prompt","")

        user_story = row.get("Prompt","")

        corrected = False

        for qe_col in QE_COLUMNS:
            value = row[qe_col]

            if not is_valid(value, qe_col):
                corrected = True
                question = f"{qe_col} question"
                prompt = make_correction_prompt(user_story, diagram_code, value, question)
                new_value = query_model(model_name, prompt)
                new_value = new_value[:new_value.find(" ")]
                new_value = "".join(filter(str.isdigit, new_value))
                if not new_value:
                    new_value = "1"  
                df.at[idx, qe_col] = int(new_value)
                print(f"Corrected {qe_col} for {model_name} ({generated_by}): {value} -> {new_value}")

        if corrected:
            df.to_csv(csv_path, index=False)

def main():
    for file in os.listdir(EVAL_DIR):
        if file.endswith(".csv"):
            csv_path = os.path.join(EVAL_DIR, file)
            print(f"Checking {csv_path}...")
            correct_csv(csv_path)
            print(f"Finished {csv_path}")

if __name__ == "__main__":
    main()