import os
import pandas as pd
import numpy as np
from collections import defaultdict

EVAL_DIR = "evaluation_outputs/"

def normalize_row(row):
    try:
        return np.array([
            float(1 if row["QE1"] == "y" or row["QE1"] == "Y" or  row["QE1"] == "1" else 0),
            (float(row["QE2"]) - 1) / 9,
            (float(row["QE3"]) - 1) / 9,
            (float(row["QE4"]) - 1) / 9,
            float(1 if row["QE5"] == "y" or row["QE5"] == "Y" or row["QE5"] == "1" else 0)
        ])
    except:
        return None



def pearson_r(a, b):
    a = np.array(a, dtype=float)
    b = np.array(b, dtype=float)

    if np.std(a) == 0 or np.std(b) == 0:
        return np.nan

    return np.corrcoef(a, b)[0, 1]

def main():
    correlations = defaultdict(lambda: {"human": [], "model": []})
    fails = 0

    for file in os.listdir(EVAL_DIR):
        if not file.endswith(".csv"):
            continue

        path = os.path.join(EVAL_DIR, file)
        df = pd.read_csv(path)

        for source in ["GPT", "TOOL"]:
            df_src = df[df["Generated by"] == source]
            if df_src.empty:
                continue

            human_rows = df_src[df_src["Model"] == "Human"]
            if human_rows.empty:
                continue

            human_vec = normalize_row(human_rows.iloc[0])
            if human_vec is None:
                continue

            for _, row in df_src.iterrows():
                if row["Model"] == "Human":
                    continue

                model_vec = normalize_row(row)
                if model_vec is None:
                    fails += 1
                    continue

                model_name = row["Model"]

                correlations[model_name]["human"].extend(human_vec)
                correlations[model_name]["model"].extend(model_vec)


    print("\n=== FINAL PEARSON CORRELATION (PAIRED DATA) ===")

    results = []
    for model, data in correlations.items():
        h = np.array(data["human"])
        m = np.array(data["model"])
        r = pearson_r(h, m)
        results.append((model, r, len(h)))

    results.sort(key=lambda x: (np.nan_to_num(x[1], nan=-2)), reverse=True)

    for model, r, n in results:
        print(f"{model:20s}  r = {r:.4f}   n = {n}")

    print(f"\nfails due to errors: {fails}")


if __name__ == "__main__":
    main()

    