import os
import pandas as pd
import numpy as np
from collections import defaultdict

EVAL_DIR = "evaluation_outputs/"

def normalize_row(row):
    try:
        return np.array([
            float(1 if row["QE1"] == "y" or row["QE1"] == "Y" or  row["QE1"] == "1" else 0),
            (float(row["QE2"]) - 1) / 9,
            (float(row["QE3"]) - 1) / 9,
            (float(row["QE4"]) - 1) / 9,
            float(1 if row["QE5"] == "y" or row["QE5"] == "Y" or row["QE5"] == "1" else 0)
        ])
    except:
        return None



def pearson_r(a, b):
    a = np.array(a, dtype=float)
    b = np.array(b, dtype=float)

    if np.std(a) == 0 or np.std(b) == 0:
        return np.nan

    return np.corrcoef(a, b)[0, 1]

def main():
    fails = 0
    correlations = defaultdict(list)

    for file in os.listdir(EVAL_DIR):
        if not file.endswith(".csv"):
            continue

        path = os.path.join(EVAL_DIR, file)
        df = pd.read_csv(path)

        for source in ["GPT", "TOOL"]:
            df_src = df[df["Generated by"] == source]

            if df_src.empty:
                continue

            human_row = df_src[df_src["Model"] == "Human"]
            if human_row.empty:
                continue

            human_vec = normalize_row(human_row.iloc[0])

            for _, row in df_src.iterrows():
                if row["Model"] == "Human":
                    continue

                model = row["Model"]
                model_vec = normalize_row(row)
                if model_vec is None:
                    # print(row)
                    # fails += 1
                    continue

                r = pearson_r(human_vec, model_vec)
                if not np.isnan(r):
                    correlations[model].append(r) 
                else:
                    fails += 1
                    print(f"dojebany model {model} pre story {file} a kod gen by {source} problem je {human_vec} a {model_vec}")

    for model, values in sorted(
        correlations.items(),
        key=lambda x: np.mean(x[1]),
        reverse=True
    ):
        print(f"{model}: mean r = {np.mean(values):.4f} (n={len(values)})")
        # print(fails)

        

if __name__ == "__main__":
    main()
    