import os
import pandas as pd
import numpy as np
from collections import defaultdict
from results import *


EVAL_DIR = "evaluation_outputs/"

def normalize_row(row):
        qe1 = 1.0 if str(row["QE1"]).strip().lower() in ("y", "1") else 0.0
        qe2 = (float(row["QE2"]) - 1) / 9
        qe3 = (float(row["QE3"]) - 1) / 9
        qe4 = (float(row["QE4"]) - 1) / 9
        qe5 = 1.0 if str(row["QE5"]).strip().lower() in ("y", "1") else 0.0
        return np.array([qe1, qe2, qe3, qe4, qe5], dtype=float)




def pearson_r(a, b):
    a = np.array(a, dtype=float)
    b = np.array(b, dtype=float)

    if np.std(a) == 0 or np.std(b) == 0:
        return np.nan

    return np.corrcoef(a, b)[0, 1]

def main():
    correlations = defaultdict(lambda: {"human": [], "model": []})
    fails = 0

    for file in os.listdir(EVAL_DIR):
        if not file.endswith(".csv"):
            continue

        path = os.path.join(EVAL_DIR, file)
        df = pd.read_csv(path)

        for source in ["GPT", "TOOL"]:
            df_src = df[df["Generated by"] == source]
            if df_src.empty:
                continue

            human_rows = df_src[df_src["Model"] == "Human"]
            if human_rows.empty:
                continue

            human_vec = normalize_row(human_rows.iloc[0])

            for _, row in df_src.iterrows():
                if row["Model"] == "Human":
                    continue

                model_vec = normalize_row(row)

                if model_vec is None:
                    fails += 1
                    continue

                    

                model_name = row["Model"]

                correlations[model_name]["human"].append(human_vec)
                correlations[model_name]["model"].append(model_vec)


    print("\n=== FINAL PEARSON CORRELATION (PAIRED DATA) ===")

    results = []
    for model, data in correlations.items():
        h = np.vstack(data["human"])
        m = np.vstack(data["model"])

        r = pearson_r(h.flatten(), m.flatten())
        results.append((model, r, len(h)))

    results.sort(key=lambda x: (np.nan_to_num(x[1], nan=-2)), reverse=True)

    for model, r, n in results:
        print(f"{model:20s}  r = {r:.4f}   n = {n}")

    print(f"\nfails due to errors: {fails}")


if __name__ == "__main__":
    main()

    