import os
import pandas as pd
import csv
from router import query_model

TOOL_DIR = r"data-folder\Results\Our Tool\Scripts"

MODELS = [
    "llama3.1:8b",
    "mistral",

    "gpt-4o-mini",
    "gpt-5",

    "azure/gpt-4.1",
    "azure/gpt-4.1-mini",
    "azure/gpt-4o",
    "azure/gpt-5.1",
    "devstral-small-2",
    "Gemma3-27b",
    "google/claude-haiku-4-5",
    "google/claude-sonnet-4-5",
    "google/gemini-2.5-flash",
    "google/gemini-2.5-pro",
    "GPT-oss-120b",
    "GPT-oss-20b",
    "Granite-4.0-tiny",
    "Llama-3.1-70b",
    "minimax-m2.1",
    "Ministral-3-14B-Instruct",
    "Mistral-Small-3.2-24B-Instruct",
    "ollama-embedding-qwen3-06",
    "vision/Qwen3-32b-VL"
]


def make_prompt(user_story: str, generated_code: str) -> str:
    return f"""
You are an assistant that evaluates a PlantUML sequence diagram based on a given user story.

USER STORY:
{user_story}

SEQUENCE DIAGRAM (PlantUML):
{generated_code}

Evaluate using:

QE1: Yes/No
QE2: 1-10
QE3: 1-10
QE4: 1-10
QE5: Yes/No

Return exactly:

QE1: ...
QE2: ...
QE3: ...
QE4: ...
QE5: ...
"""


def parse_response(response: str) -> dict:
    qe = {"QE1": "", "QE2": "", "QE3": "", "QE4": "", "QE5": ""}

    for line in response.splitlines():
        t = line.strip()
        if t.startswith("QE1:"):
            qe["QE1"] = t.replace("QE1:", "").strip()[:1]
        elif t.startswith("QE2:"):
            qe["QE2"] = t.replace("QE2:", "").strip()[:2]
        elif t.startswith("QE3:"):
            qe["QE3"] = t.replace("QE3:", "").strip()[:2]
        elif t.startswith("QE4:"):
            qe["QE4"] = t.replace("QE4:", "").strip()[:2]
        elif t.startswith("QE5:"):
            qe["QE5"] = t.replace("QE5:", "").strip()[:1]

    return qe



def evaluate_diagram(user_story, diagram_code, generated_by, writer):
    for model_name in MODELS:

        print(f"Model: {model_name} evaluating {generated_by}")

        prompt = make_prompt(user_story, diagram_code)
        response = query_model(model_name, prompt)

        qe = parse_response(response)

        writer.writerow([
            generated_by,
            model_name,
            qe["QE1"],
            qe["QE2"],
            qe["QE3"],
            qe["QE4"],
            qe["QE5"],
            prompt
        ])



def write_human_scores(row, writer):
    writer.writerow([
        "GPT",
        "Human",
        row["QE1 (GPT)"],
        row["QE2 (GPT)"],
        row["QE3 (GPT)"],
        row["QE4 (GPT)"],
        row["QE5 (GPT)"],
        "None"
    ])

    writer.writerow([
        "Tool",
        "Human",
        row["QE1(Our Tool)"],
        row["QE2 (Our Tool)"],
        row["QE3 (Our Tool)"],
        row["QE4 (Our Tool)"],
        row["QE5 (Our Tool)"],
        "None"
    ])



def evaluate_story(idx, row):

    user_story = row["User story"]

    with open(TOOL_DIR + f"/SD{idx + 1}.txt") as file:
        generated_tool = file.read()

    generated_gpt = row["GPT Generated seq in PlantUML format"]

    os.makedirs("evaluation_outputs", exist_ok=True)
    csv_path = os.path.join("evaluation_outputs", f"story_{idx}.csv")

    with open(csv_path, "w", encoding="utf-8", newline="") as file:
        writer = csv.writer(file)

        writer.writerow(["Generated by", "Model", "QE1", "QE2", "QE3", "QE4", "QE5", "Prompt"])

        write_human_scores(row, writer)

        evaluate_diagram(user_story, generated_tool, "Tool", writer)
        evaluate_diagram(user_story, generated_gpt, "GPT", writer)

    print(f"Finished Story {idx}")



if __name__ == "__main__":

    df = pd.read_csv(r"data-folder\Evaluation\Final CSV_gpt.csv")

    for idx, row in df.iterrows():
        print(f"\n=== Evaluating Story {idx} ===")
        evaluate_story(idx, row)