import os
import pandas as pd
import csv
from router import query_model

TOOL_DIR = r"data-folder\Results\Our Tool\Scripts"

MODELS = [
    "llama3.1:8b",
    "mistral",

    "gpt-4o-mini",
    "gpt-5",

    "azure/gpt-4.1",
    "azure/gpt-4.1-mini",
    "azure/gpt-4o",
    "azure/gpt-5.1",
    "devstral-small-2",
    "Gemma3-27b",
    "google/claude-haiku-4-5",
    "google/claude-sonnet-4-5",
    "google/gemini-2.5-flash",
    "google/gemini-2.5-pro",
    "GPT-oss-120b",
    "GPT-oss-20b",
    "Granite-4.0-tiny",
    "Llama-3.1-70b",
    "minimax-m2.1",
    "Ministral-3-14B-Instruct",
    "Mistral-Small-3.2-24B-Instruct",
    "ollama-embedding-qwen3-06",
    "vision/Qwen3-32b-VL"
]



def make_prompt(user_story: str, generated_code: str) -> str:
    return f"""
You are an assistant that evaluates a PlantUML sequence diagram based on a given user story.

USER STORY:
{user_story}

SEQUENCE DIAGRAM (PlantUML):
{generated_code}

Evaluate using:

QE1: 0/1 (Yes/No)
QE2: 1-10
QE3: 1-10
QE4: 1-10
QE5: 0/1 (Yes/No)

Return exactly:

QE1: ...
QE2: ...
QE3: ...
QE4: ...
QE5: ...
"""




def parse_response(response: str) -> dict:
    qe = {"QE1": "0", "QE2": "1", "QE3": "1", "QE4": "1", "QE5": "0"}

    for line in response.splitlines():
        t = line.strip()
        if ":" not in t:
            continue
        key, val = t.split(":", 1)
        val = val.strip()

        digits = "".join(filter(str.isdigit, val))

        if key == "QE1" or key == "QE5":
            qe[key] = "1" if digits == "" or digits[0] == "1" else "0"
        elif key in ["QE2", "QE3", "QE4"]:
            if digits == "":
                qe[key] = "1"
            else:
                n = int(digits)
                qe[key] = str(min(max(n, 1), 10))
    return qe



def write_human_scores(row, writer):
    writer.writerow([
        "GPT",
        "Human",
        row["QE1 (GPT)"],
        row["QE2 (GPT)"],
        row["QE3 (GPT)"],
        row["QE4 (GPT)"],
        row["QE5 (GPT)"],
        "None"
    ])
    writer.writerow([
        "Tool",
        "Human",
        row["QE1(Our Tool)"],
        row["QE2 (Our Tool)"],
        row["QE3 (Our Tool)"],
        row["QE4 (Our Tool)"],
        row["QE5 (Our Tool)"],
        "None"
    ])



def evaluate_diagram(user_story, diagram_code, generated_by, csv_path):
    if os.path.exists(csv_path):
        df_existing = pd.read_csv(csv_path)
        existing_pairs = set(zip(df_existing["Generated by"], df_existing["Model"]))
    else:
        existing_pairs = set()

    with open(csv_path, "a", encoding="utf-8", newline="") as file:
        writer = csv.writer(file)
        if file.tell() == 0:
            writer.writerow(["Generated by", "Model", "QE1", "QE2", "QE3", "QE4", "QE5", "Prompt"])

        for model_name in MODELS:
            if (generated_by, model_name) in existing_pairs:
                print(f"Skipping {model_name} for {generated_by} — already done")
                continue
            print(f"Model: {model_name} evaluating {generated_by}")
            prompt = make_prompt(user_story, diagram_code)
            response = query_model(model_name, prompt)
            qe = parse_response(response)

            writer.writerow([
                generated_by,
                model_name,
                qe["QE1"],
                qe["QE2"],
                qe["QE3"],
                qe["QE4"],
                qe["QE5"],
                prompt
            ])

            file.flush()
            os.fsync(file.fileno())




def evaluate_story(idx, row):
    user_story = row["User story"]

    with open(TOOL_DIR + f"/SD{idx + 1}.txt") as file:
        generated_tool = file.read()

    generated_gpt = row["GPT Generated seq in PlantUML format"]

    os.makedirs("evaluation_outputs", exist_ok=True)
    csv_path = os.path.join("evaluation_outputs", f"story_{idx}.csv")

    with open(csv_path, "a", encoding="utf-8", newline="") as file:
        writer = csv.writer(file)
        if file.tell() == 0:
            writer.writerow(["Generated by", "Model", "QE1", "QE2", "QE3", "QE4", "QE5", "Prompt"])
        write_human_scores(row, writer)

    evaluate_diagram(user_story, generated_tool, "Tool", csv_path)
    evaluate_diagram(user_story, generated_gpt, "GPT", csv_path)

    print(f"Finished Story {idx}")



if __name__ == "__main__":
    df = pd.read_csv(r"data-folder\Evaluation\Final CSV_gpt.csv")

    for idx, row in df.iterrows():
        print(f"\n=== Evaluating Story {idx} ===")
        evaluate_story(idx, row)